Added '-a' option for performing actions on all mailboxes, including a check_usage_conflict_all_mailboxes() guard function for options that don't support actions on all mailboxes. Currently, the '-a' option is only supported for full indexing ('-i'), so added list_servers(), list_server_mailboxes(), and index_all_mailboxes() functions. I reordered options parsing to help me remember the order they should be provided and updated usage(). Also silenced a few shellcheck(1) warnings via inline comments.

diff --git a/libexec/claws-mail-labels b/libexec/claws-mail-labels
--- a/libexec/claws-mail-labels
+++ b/libexec/claws-mail-labels
@@ -31,6 +31,7 @@
 
 _tool="$(basename "$0")"
 
+_all_mailboxes="false"
 _imapcache="${HOME}/.claws-mail/imapcache"
 _labelscache="${HOME}/.claws-mail/labelscache"
 _server="$CM_LABELS_SERVER"
@@ -50,6 +51,22 @@ parse_message_path_mailbox_server() {
   _mailbox="${_mailbox%%/*}"
 }
 
+# list all servers for which mailboxes are indexed
+list_servers() {
+  find "$_labelscache" -type d -mindepth 1 -maxdepth 1 | while IFS= read -r _line ; do
+    [ -n "$_line" ] && basename "$_line"
+  done
+}
+
+# given a server, list all the mailboxes which are indexed
+list_server_mailboxes() {
+  [ -z "$_server" ] && exit 1
+
+  find "${_labelscache}/${_server}" -type d -mindepth 1 -maxdepth 1 | while IFS="" read -r _line ; do
+    [ -n "$_line" ] && basename "$_line"
+  done
+}
+
 # given a mailbox, find its IMAP server
 find_mailbox_server() {
   [ -z "$_mailbox" ] && exit 1
@@ -65,6 +82,7 @@ mairixrc_path() {
   [ -z "$_mailbox" ] && exit 1
 
   printf "%s/%s/%s/mairixrc" "$_labelscache" "$_server" "$_mailbox"
+  # shellcheck disable=SC3045
   [ -n "$_variant" ] && printf "-%s" "$_variant"
 }
 
@@ -111,7 +129,15 @@ EOF
 
 # print usage instructions
 usage() {
-  printf "Usage: %s [-h] [-m mailbox [-i]] [-f file [-r | -l]]\n" "$_tool"
+  printf "Usage: %s [-h] [[-a | -m mailbox] [-i]] [-f file [-r | -l]]\n" "$_tool"
+}
+
+check_usage_conflict_all_mailboxes() {
+  _option="$1"
+  $_all_mailboxes \
+    && printf "%s: The '-%s' option cannot be combined with the '-a' option!\n" "$_tool" "$_option" \
+    && usage \
+    && exit 2
 }
 
 # full index of a mailbox's MH directory, including purging entries
@@ -119,7 +145,19 @@ index_mailbox() {
   _fast="${1:-false}"
   _purge="${2:-false}"
 
+  # shellcheck disable=SC2046
   nice mairix -v -f "$(mairixrc_path)" $($_fast && echo '-F') $($_purge && echo '-p')
+}
+
+# full index of _all_ mailboxes for _all_ servers, including purging entries
+index_all_mailboxes() {
+  # shellcheck disable=SC2030
+  list_servers | while IFS= read -r _server ; do
+    # shellcheck disable=SC2030
+    list_server_mailboxes | while IFS= read -r _mailbox ; do
+      index_mailbox false true
+    done
+  done
 }
 
 # TODO: fast reindex of just a specific label/folder within an MH directory
@@ -144,6 +182,7 @@ reindex_label() {
 reindex_labels_for_message_path() {
   list_labels_for_message_path | while IFS="" read -r _label ; do
     [ -z "$_label" ] && continue
+    # shellcheck disable=SC2031
     reindex_label "${_server}/${_mailbox}/${_label}"
   done
 }
@@ -154,6 +193,8 @@ list_labels_for_id() {
   # print labels/folders which contain the message
   mairix -f "$(mairixrc_path)" "m:${_message_id}" | while IFS="" read -r _label ; do
     _message_filename="$(basename "$_label")"
+
+    # shellcheck disable=SC2031
     _label_name="${_label##"$_imapcache"/"$_server"/"$_mailbox"/}"
     _label_name="${_label_name%%/"$_message_filename"}"
     printf "%s\n" "$_label_name"
@@ -172,27 +213,42 @@ list_labels_for_message_path() {
 }
 
 main() {
-  while getopts f:hirlm: _name ; do
+  while getopts af:hirlm: _name ; do
     case $_name in
-      # parse server & mailbox from message path
-      f)
-        _message_path="$OPTARG"
-        parse_message_path_mailbox_server
-        ;;
       # help/usage
       h) usage && exit ;;
-      # full index
-      i) index_mailbox false true ;;
-      # list labels for an email message file
-      l) list_labels_for_message_path ;;
+      # process all mailboxes across all servers
+      a) _all_mailboxes="true" ;;
       # specify mailbox name
       m)
+        check_usage_conflict_all_mailboxes "$_name"
         _mailbox="$OPTARG"
         find_mailbox_server
         init_mairixrc
         ;;
-      # reindex a specific label/folder
+        # full index (requires either '-a' or '-m')
+      i)
+        if $_all_mailboxes ; then
+          index_all_mailboxes
+        else
+          index_mailbox false true
+        fi
+        ;;
+      # parse server & mailbox from message path
+      f)
+        check_usage_conflict_all_mailboxes "$_name"
+        _message_path="$OPTARG"
+        parse_message_path_mailbox_server
+        ;;
+      # list labels for an email message file (requires '-f')
+      l)
+        check_usage_conflict_all_mailboxes "$_name"
+        list_labels_for_message_path
+        ;;
+      # reindex a specific label/folder (requires '-f')
       r)
+        check_usage_conflict_all_mailboxes "$_name"
+
         # TODO: override reindexing of individual folders with a non-purge, fast, full index of the mailbox
         # until I update mairix to not flag messages in other folders as stale/dead. See:
         # <https://github.com/vandry/mairix/issues/40>
